version: "2.4"

services:
  backend:
    image: ghcr.io/csiszaralex/Voter-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ADMINS=Viktor,Admin,Nori,Nóri
    networks:
      - app-network
    restart: always

  frontend:
    image: ghcr.io/csiszaralex/Voter-frontend:latest
    depends_on:
      - backend
    networks:
      - app-network
      - proxy_network
    restart: always
    labels:
      - "traefik.enable=true"
      # Router szabály: Milyen domainre figyeljen?
      - "traefik.http.routers.voter-app.rule=Host(`vote.csalex.dev`)"
      # Melyik belépési ponton? (HTTPS)
      - "traefik.http.routers.voter-app.entrypoints=websecure"
      # Használja a Let's Encrypt feloldót (amit a traefikben 'myresolver'-nek neveztünk)
      - "traefik.http.routers.voter-app.tls.certresolver=myresolver"
      # Melyik porton hallgat a konténer BELÜL? (Az Nginxed a 80-ason van)
      - "traefik.http.services.voter-app.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy_network"

networks:
  app-network:
    driver: bridge
  proxy_network:
    external: true
